#ifndef DEFINESOPENCV_H
#define DEFINESOPENCV_H

//OpenCV:
#include <opencv2/opencv.hpp>

//NOT WORK! (для работы требуется объявление всех переменных)
//#define GET_CV_CAP_PROP_POS_AVI_RATIO() (CV_MAJOR_VERSION < 4 ? CV_CAP_PROP_POS_AVI_RATIO : cv::CAP_PROP_POS_AVI_RATIO)

#if CV_MAJOR_VERSION < 3
#define MY_CV_CAP_PROP_POS_AVI_RATIO CV_CAP_PROP_POS_AVI_RATIO
#define MY_CV_CAP_PROP_POS_FRAMES CV_CAP_PROP_POS_FRAMES
#define MY_CV_CAP_PROP_FRAME_COUNT CV_CAP_PROP_FRAME_COUNT
#define MY_CV_CAP_PROP_FRAME_WIDTH CV_CAP_PROP_FRAME_WIDTH
#define MY_CV_CAP_PROP_FRAME_HEIGHT CV_CAP_PROP_FRAME_HEIGHT
#define MY_CV_CAP_PROP_FPS CV_CAP_PROP_FPS
#define MY_CV_CAP_PROP_POS_MSEC CV_CAP_PROP_POS_MSEC
#define MY_CV_RECT2F cv::Rect
#define MY_CV_RECT2I cv::Rect
#define MY_CV_FOURCC CV_FOURCC
#define MY_CV_RGB2BGR CV_RGB2BGR
#define MY_CV_BGR2RGB CV_BGR2RGB
#define MY_CV_BGR2HSV CV_BGR2HSV
#define MY_CV_HSV2BGR CV_HSV2BGR
#define MY_CV_BGRA2BGR CV_BGRA2BGR
#define MY_CV_BGR2BGRA CV_BGR2BGRA
#define MY_CV_BGR2GRAY CV_BGR2GRAY
#define MY_CV_GRAY2BGR CV_GRAY2BGR
#define MY_CV_SIZE cvSize
#define MY_CV_COEFF_FPS 0.5//Ошибка в opencv! (потому так), сейчас хз!
#define MY_CV_ACCESS_FAST cv::ACCESS_FAST

#elif 3 <= CV_MAJOR_VERSION && CV_MAJOR_VERSION < 4//
#define MY_CV_CAP_PROP_POS_AVI_RATIO CV_CAP_PROP_POS_AVI_RATIO
#define MY_CV_CAP_PROP_POS_FRAMES CV_CAP_PROP_POS_FRAMES
#define MY_CV_CAP_PROP_FRAME_COUNT CV_CAP_PROP_FRAME_COUNT
#define MY_CV_CAP_PROP_FRAME_WIDTH cv::CAP_PROP_FRAME_WIDTH
#define MY_CV_CAP_PROP_FRAME_HEIGHT cv::CAP_PROP_FRAME_HEIGHT
#define MY_CV_CAP_PROP_FPS CV_CAP_PROP_FPS
#define MY_CV_CAP_PROP_POS_MSEC CV_CAP_PROP_POS_MSEC
#define MY_CV_RECT2F cv::Rect2f
#define MY_CV_RECT2I cv::Rect2i
#define MY_CV_FOURCC CV_FOURCC
#define MY_CV_RGB2BGR CV_RGB2BGR
#define MY_CV_BGR2RGB CV_BGR2RGB
#define MY_CV_BGR2HSV CV_BGR2HSV
#define MY_CV_HSV2BGR CV_HSV2BGR
#define MY_CV_BGRA2BGR CV_BGRA2BGR
#define MY_CV_BGR2BGRA CV_BGR2BGRA
#define MY_CV_BGR2GRAY CV_BGR2GRAY
#define MY_CV_GRAY2BGR CV_GRAY2BGR
#define MY_CV_SIZE cvSize
#define MY_CV_COEFF_FPS 0.5//Ошибка в opencv! (потому так), сейчас хз!
#define MY_CV_ACCESS_FAST cv::ACCESS_FAST

#else
#define MY_CV_CAP_PROP_POS_AVI_RATIO cv::CAP_PROP_POS_AVI_RATIO
#define MY_CV_CAP_PROP_POS_FRAMES cv::CAP_PROP_POS_FRAMES
#define MY_CV_CAP_PROP_FRAME_COUNT cv::CAP_PROP_FRAME_COUNT
#define MY_CV_CAP_PROP_FRAME_WIDTH cv::CAP_PROP_FRAME_WIDTH
#define MY_CV_CAP_PROP_FRAME_HEIGHT cv::CAP_PROP_FRAME_HEIGHT
#define MY_CV_CAP_PROP_FPS cv::CAP_PROP_FPS
#define MY_CV_CAP_PROP_POS_MSEC cv::CAP_PROP_POS_MSEC
#define MY_CV_RECT2F cv::Rect2f
#define MY_CV_RECT2I cv::Rect2i
#define MY_CV_FOURCC cv::VideoWriter::fourcc
#define MY_CV_RGB2BGR cv::COLOR_RGB2BGR
#define MY_CV_BGR2RGB cv::COLOR_BGR2RGB
#define MY_CV_BGR2HSV cv::COLOR_BGR2HSV
#define MY_CV_HSV2BGR cv::COLOR_HSV2BGR
#define MY_CV_BGRA2BGR cv::COLOR_BGRA2BGR
#define MY_CV_BGR2BGRA cv::COLOR_BGR2BGRA
#define MY_CV_BGR2GRAY cv::COLOR_BGR2GRAY
#define MY_CV_GRAY2BGR cv::COLOR_GRAY2BGR
#define MY_CV_SIZE cv::Size
#define MY_CV_COEFF_FPS 1.5
//Если бы исправили, то было бы 1.0 (когда то же работало...),
//однако в итоге: аналоговая камера 1М (fps = 25) -> 1.5, цифровая webcam log.270 (fps = 20) -> 0.66
#define MY_CV_ACCESS_FAST cv::AccessFlag::ACCESS_FAST
#endif

#endif // DEFINESOPENCV_H
